### ISSUE TITLE
Tracking doc: shipping built-in type definitions

### ISSUE THREAD

**Issue by jackfranklin** [puppeteer/puppeteer#6124]
Now the codebase is in TypeScript we can ship type definitions built-in to the library and deprecate the 3rd party DefinitelyTyped version. To be clear, we are very grateful to those who have worked hard on providing types, but if we can ship them built-in that's a better experience for all.

This proposal is also related to [#6118](https://github.com/puppeteer/puppeteer/issues/6118) as shipping new docs will make it easier to use our TS defs as the docs will document them all.

The steps to doing this are roughly like so:

- [ ] Port over the most valuable type defs from DefinitelyTyped. The main functions that we have inferior types for now are `$eval`, `$$eval` and similar.
- [x] Use API Extractor to rollup all our types into one large `puppeteer.d.ts` file that we can ship as the typings. This will enable people to import types directly from `puppeteer` rather than `import {TypeX} from 'puppeteer/lib/...'` which we do not want to support (we do not consider internal file structure changes as breaking and would like to keep it that way).
- [x] Update our `package.json` to point the `types` property to our `puppeteer.d.ts` file (as documented in the [TS handbook](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)).
- [ ] Ship a major version release with the types in.
- [ ] Gather feedback (I expect there will be bugs in our type-defs, or issues to resolve) and iterate in some minor releases with type improvements.

_If you're reading and would like to get involved, that's great and very welcome, but please ping me first to ensure we're not wasting effort by doing the same work!_

**Comment by christian-bromann** [comment]
@jackfranklin what would be the best way to use built in types right now already? While I can import the `d.ts` typings directly I struggle with that in certain cases, e.g. when using `evaluate`. To reproduce:

- `mkdir tmp && cd tmp && npm i typescript puppeteer-core @types/puppeteer-core`
- create this file:
    ```ts
    import puppeteer from 'puppeteer-core'
    import PuppeteerNode from 'puppeteer-core/lib/cjs/puppeteer/node'

    const p: typeof PuppeteerNode = puppeteer as unknown as typeof PuppeteerNode;

    (async () => {
      const browser = await p.launch();
      const page = await browser.newPage();
      await page.goto('https://example.com');

      // Get the "viewport" of the page, as reported by the page.
      const someNumber = await page.evaluate<(a: number, b: number) => number>(
        (a: number, b: number): number => a * b,
      1, 2)

      console.log('Dimensions:', someNumber);

      await browser.close();
    })();
    ```

It is not possible to provide types for `evaluate` due to:

```
Type '(a: number, b: number) => number' does not satisfy the constraint 'EvaluateFn<unknown>'.
  Type '(a: number, b: number) => number' is not assignable to type '(arg1: unknown, ...args: unknown[]) => unknown'.
    Types of parameters 'a' and 'arg1' are incompatible.
      Type 'unknown' is not assignable to type 'number'.ts(2344)
```

any hints?

**Comment by christian-bromann** [comment]
@jackfranklin what would be the best way to use built in types right now already? While I can import the `d.ts` typings directly I struggle with that in certain cases, e.g. when using `evaluate`. To reproduce:

- `mkdir tmp && cd tmp && npm i typescript puppeteer-core @types/puppeteer-core`
- `npx tsc --init`
- create this file:
    ```ts
    import puppeteer from 'puppeteer-core'
    import PuppeteerNode from 'puppeteer-core/lib/cjs/puppeteer/node'

    const p: typeof PuppeteerNode = puppeteer as unknown as typeof PuppeteerNode;

    (async () => {
      const browser = await p.launch();
      const page = await browser.newPage();
      await page.goto('https://example.com');

      // Get the "viewport" of the page, as reported by the page.
      const someNumber = await page.evaluate<(a: number, b: number) => number>(
        (a: number, b: number): number => a * b,
      1, 2)

      console.log('Dimensions:', someNumber);

      await browser.close();
    })();
    ```

It is not possible to provide types for `evaluate` due to:

```
Type '(a: number, b: number) => number' does not satisfy the constraint 'EvaluateFn<unknown>'.
  Type '(a: number, b: number) => number' is not assignable to type '(arg1: unknown, ...args: unknown[]) => unknown'.
    Types of parameters 'a' and 'arg1' are incompatible.
      Type 'unknown' is not assignable to type 'number'.ts(2344)
```

any hints?
